<?php
/**
 * @file Module.
 */

use Drupal\embed\Entity\EmbedButton;

/**
 * Implements hook_install().
 */
function paragraphs_inline_entity_form_install() {
  // Set the default icon.
  $icon = drupal_get_path('module', 'paragraphs_inline_entity_form') . '/images/paragraph_icon.png';
  $data = file_get_contents($icon);
  if ($file = file_save_data($data, 'public://paragraph_icon.png', FILE_EXISTS_REPLACE)) {
    if ($embed_button = EmbedButton::load('paragraphs_inline_entity_form')) {
      $embed_button->set('icon_uuid', $file->uuid());
      $embed_button->save();
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function paragraphs_inline_entity_form_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  /* @var Drupal\Core\Entity\FieldableEntityInterface $entity */
  $formObject = $form_state->getFormObject();
  if ($formObject instanceof \Drupal\Core\Entity\EntityFormInterface) {
    $form['#attached']['library'][] = 'paragraphs_inline_entity_form/dialog';
  }
}
